language: python
python:
- '3.5'
env:
- TOXENV=py35
- TOXENV=pep8
before_install:
- pip install tox
script:
- tox
after_success:
- coveralls
deploy:
  provider: pypi
  user: Ebag333
  password:
    secure: VBT0uxngnE9LuxXYCGzBq2zDLlq9wrSs6g2BAN7UUZFEiaRdHAPB25Igjm/ZMYikTcyT/v84Ro8yJ9jBcFdxMaP1JZu0zkqXpYYRUAGRAGNn7/CdiORr6ypu8w/5TcfpLWFLLUbLaAqNNxEmxZuzbIdxdaDhtE6AUkEMf9H9Fr11A7Dh5FbW0wMATkujXb63GTDNCM7YBhMTgVisSoG3f44Rx0edrLClaeZ9cpda4TZzAPFizZmqvMUiwxeuZQQbwHArmGQQEUUhMJx8ptU4RH/5vR/EePaCuBrg4KbjLB3xe8Wpt/N0LVcljC9J4Ic76GHAgnm6lI1rAknlm6ULZxjO8d/OtiJMXrjvhD9rC+CpL/hFCKDvKAaiz3gJt9g4IEjuka15NHkP2aWsCCxvjb9MkZlLK3pGPURsWUuzeciEL6UpNB5Mi6K8nmUn66HbBCxr5gJvNsIGverBcYLphmbmfzjQmzteNs8SkFo+/iRPb+SrubJ2QhLPgQW3DUAMG4sGzuiKWoCxrG+TJk7P7EceaUpllyZKHSlBelvn9vBB9xriDQrLcE0zYmIPkqM021InsLv09++RqXv5/W8KM3ucVJ4jfQhjEioBeOCJGt1jDmngxbYfAkg9LbxxvmifQlO8QtC0xV6IqCYkq+e5uPnprT+opJO9kU+ZuOt+zZo=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Ebag333/EVE_Gnosis
