language: python
python:
- '3.5'
env:
- TOXENV=py35
- TOXENV=pep8
before_install:
- pip install tox
script:
- tox
after_success:
- coveralls
deploy:
  provider: pypi
  user: Ebag333
  password:
    secure: y1QYTyFxOKE/BGw19w1p2+z2P+20U07fJDmMMtm6k0lpPz1QDhnuqeYyI8IWXg9zrV81kq9WyicrhTzKq6h6RvoBFpdv2l8daHz9Oq6pezz+Y0NRSAwqQ16t0rakvKxGj+WIDN6JIWirtGJbDr/VFHgypk4ZnIUyPCBqhUaX24nf9ts8jn+/CwKCKcaOvc7yQcIJWcv1eI0kTm/GYcep/iIovnoVEtWxMC2ZrHxqvsGfWFR3ZMBXD0LgBTfYrsRTBC1PQATBsty5LJ/KbG7cUo18XH2t1bbfMJVkLxKO0k135WE9zlkv9RrNqzVFtz/G3IYMxfbYvxvUNUioRX7XI7nLOm3wpRM0+Ov49BscDEP4HCi1i6K5pPHHroOvEOr2pR3fiNbVdU5bHHeDG0R+s1XDcqNoxn4zkbcStboP2g4ngJdWqR20k6KFc8ubPcoMUHkjbSYHOjcT58jb/8m8e519Nwqf3pvJUlz0ciqSKktX0lzkMNdko7/88xuMnX7eD3KTtfuhiNvhkQTmub3ELPSEqucfpKA47+0vo+vxeHksxPRuym4DxoBeVcYiqADrjonE4cGFf7XlLt4Yo+4buhbsFgdF8GfySGdcGhfgRV+Q8IIh3bpS6wxZ1woHsYsesCgCy55NULDeUiVwvfv/gpu64tR47CEL6cEaJlrhaTs=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Ebag333/Gnosis
